In [1]:
try:
    import geopandas as gpd
except:
    !pip install geopandas

In [3]:
shp_file = 'Trafikplatser_järnväg.dbf'

In [4]:
db = gpd.read_file(shp_file)
db.head()

,Platsnamn,Signatur,Sign_text,Platstyp,Typ_beskr,Dignitet,Status,Resandeutb,Tillh_dpd,Tillh_dp,...,TL,BIS_id,BIS_typid,Kmtal,Kmtalti,Northing,Easting,Moh,Skapad,geometry
0,Kilafors,Kls,Kls,dp,Driftplats,None,Öppen,j,None,None,...,Gä,170,2,300+ 207,300+ 207,6789496.0,584314.0,58.0,20181105,POINT Z (584315.9959000004 6789494.785399999 0)
1,Härad,Häd,Häd,dp,Driftplats,None,Öppen,n,None,None,...,Nr,1492,2,56+ 943,56+ 943,6581376.0,608767.0,15.0,20181105,POINT Z (608767.4908999996 6581371.931399999 0)
2,Stehag,Sg,Sg,dp,Driftplats,None,Öppen,j,None,None,...,M,800,2,574+ 583,574+ 668,6196149.0,399549.0,64.0,20181105,POINT Z (399542.5387000004 6196150.9465 0)
3,Läggesta,Lg,Lg,dp,Driftplats,None,Öppen,j,None,None,...,Nr,1489,2,33+ 695,33+ 695,6569630.0,623710.0,21.0,20181105,POINT Z (623712.4390000002 6569628.463099999 0)
4,Liseberg,Lis,Lis,hst,None,None,None,j,Gro,None,...,G,104,10000,3+ 163,3+ 163,6399222.0,321028.0,NaN,20181105,POINT Z (321016.1025 6399230.709000001 0)

In [5]:
db.shape

(1615, 24)

# Converting to Excel file

In [11]:
# It is necessary to convert it to pandas file first
# then for the conversion, I drop the last column (geometry) and specify the column names for the new df
import pandas as pd
try:
    import xlsxwriter
except:
    !pip install xlsxwriter
df1 = pd.DataFrame(db.iloc[:,:-1].values, columns = list(db.columns.values)[:-1] )

# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('RailwayStations.xlsx', engine='xlsxwriter')

# Convert the dataframe to an XlsxWriter Excel object.
df1.to_excel(writer, sheet_name='Sheet1')

# Close the Pandas Excel writer and output the Excel file.
writer.save()